Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFood.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {



        }


        public DbSet<Food> Foods { get; set; }


        protected override void OnModelCreating(ModelBuilder builder)
        {

            foreach (var property in builder.Model.GetEntityTypes()
                .SelectMany(t => t.GetProperties())
                .Where(p => p.ClrType == typeof(decimal) || p.ClrType == typeof(decimal?)))
            {

                property.SetColumnType("decimal(18,6)");

            }
        }

    }
}

Models/ErrorViewModel.cs
using System;

namespace MyFood.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Food.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MyFood.Models
{
    public class Food
    {
        [Key]
        [StringLength(36)]
        public string Id { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        [Range(1, 100000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 6)")]
        public decimal ServingSize { get; set; }

        [Range(0, 100000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 6)")]
        public decimal Carb { get; set; }

        [Range(0, 100000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 6)")]
        public decimal Protein { get; set; }

        [Range(0, 100000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 6)")]
        public decimal Fat { get; set; }



    }

}

Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyFood.Models;

namespace MyFood.Controllers
{
    public class FoodController : Controller
    {

        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Food Food { get; set; }

        public FoodController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(string? Id)
        {

            Food = new Food();
            if (Id == null)
            {
                //Create
                return View(Food);
            }

            //Update
            Food = _db.Foods.FirstOrDefault(u => u.Id == Id);
            if (Food == null)
            {
                return NotFound();
            }

            return View(Food);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (Food.Id == null)
                {
                    //create
                    Food.Id = Guid.NewGuid().ToString();
                    _db.Foods.Add(Food);
                }
                else
                {
                    _db.Foods.Update(Food);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Food);
        }

        #region API Calls

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Foods.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string Id)
        {
            var foodFromDb = await _db.Foods.FirstOrDefaultAsync(u => u.Id == Id);
            if (foodFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Foods.Remove(foodFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion

    }
}

Controllers/FoodListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyFood.Models;

namespace MyFood.Controllers
{
    public class FoodListController : Controller
    {

        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Food Food { get; set; }

        public FoodListController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(string? Id)
        {

            Food = new Food();
            if (Id == null)
            {
                //Create
                return View(Food);
            }

            //Update
            Food = _db.Foods.FirstOrDefault(u => u.Id == Id);
            if (Food == null)
            {
                return NotFound();
            }

            return View(Food);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (Food.Id == null)
                {
                    //create
                    Food.Id = Guid.NewGuid().ToString();
                    _db.Foods.Add(Food);
                }
                else
                {
                    _db.Foods.Update(Food);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Food);
        }

        #region API Calls

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Foods.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string Id)
        {
            var foodFromDb = await _db.Foods.FirstOrDefaultAsync(u => u.Id == Id);
            if (foodFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Foods.Remove(foodFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyFood.Models;

namespace MyFood.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LogFoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFood.Controllers
{
    public class LogFoodController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Food/Index.cshtml
@{
    ViewData["Title"] = "My Food";
}


<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Food List</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Food" class="btn btn-info form-control text-white">
            Add New Food
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>ServingSize</th>
                    <th>Carbs</th>
                    <th>Protein</th>
                    <th>Fat</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/foodList.js"></script>
}

Views/FoodList/Index.cshtml
@{
    ViewData["Title"] = "My Food";
}


<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Food List</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="FoodList" class="btn btn-info form-control text-white">
            Add New Food
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>ServingSize</th>
                    <th>Carbs</th>
                    <th>Protein</th>
                    <th>Fat</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/foodList.js"></script>
}

Views/FoodList/Upsert.cshtml
@model MyFood.Models.Food

<br />
<h2 class="text-info">@(Model.Id != null ? "Edit" : "Create") Food</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post" asp-action="upsert">
        @if (Model.Id != null)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ServingSize">Serving Size</label>
            </div>
            <div class="col-6">
                <input asp-for="ServingSize" class="form-control" />
                <span asp-validation-for="ServingSize" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Carb"></label>
            </div>
            <div class="col-6">
                <input asp-for="Carb" class="form-control" />
                <span asp-validation-for="Carb" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Protein"></label>
            </div>
            <div class="col-6">
                <input asp-for="Protein" class="form-control" />
                <span asp-validation-for="Protein" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Fat"></label>
            </div>
            <div class="col-6">
                <input asp-for="Fat" class="form-control" />
                <span asp-validation-for="Fat" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Id != null ? "Update" : "Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>

    </form>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "My Food";
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/LogFood/Index.cshtml
@{
    ViewData["Title"] = "LogFood";
}

<div class="container row p-0 m-0">
    <div class="col-xs-1 text-center">
        <label id="subtractday" class="control-label"><b><</b></label>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-12 text-center">
        <label id="daylabel" class="control-label"><b>Today</b></label>
        <div class="form-group">
            <input id="datepicker" type="text" class="form-control text-center" value="@DateTime.Today.ToString("MM/dd/yyyy")" />
            <span class="text-danger"></span>
        </div>
    </div>
    <div class="col-xs-1 text-center">
        <label id="addday" class="control-label"><b>></b></label>
    </div>
</div>


<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Log Food</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="FoodList" class="btn btn-info form-control text-white">
            Add Food
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_FoodLog" class="table table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Meal</th>
                    <th>Food</th>
                    <th>kcal</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Snack</td>
                    <td>yogurt</td>
                    <td>223</td>
                </tr>
                <tr>
                    <td>Dessert</td>
                    <td>Blueberries</td>
                    <td>33</td>
                </tr>
                <tr>
                    <td>Breakfast</td>
                    <td>Apple</td>
                    <td>156</td>
                </tr>
                <tr>
                    <td>Dinner</td>
                    <td>Salmon</td>
                    <td>350</td>
                </tr>
                <tr>
                    <td>Breakfast</td>
                    <td>Coffee</td>
                    <td>2</td>
                </tr>
                <tr>
                    <td>Dessert</td>
                    <td>Wheyz</td>
                    <td>255</td>
                </tr>
                <tr>
                    <td>Lunch</td>
                    <td>Kale</td>
                    <td>1</td>
                </tr>
                <tr>
                    <td>Dinner</td>
                    <td>Broccoli</td>
                    <td>30</td>
                </tr>
                <tr>
                    <td>Snack</td>
                    <td>Carrots</td>
                    <td>2</td>
                </tr>
                <tr>
                    <td>Dessert</td>
                    <td>Almonds</td>
                    <td>99</td>
                </tr>
            </tbody>

        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/dailyLogList.js"></script>

    <link href="https://nightly.datatables.net/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />
    <script src="https://nightly.datatables.net/js/jquery.dataTables.js"></script>

    <link href="https://cdn.datatables.net/rowgroup/1.0.2/css/rowGroup.dataTables.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.datatables.net/rowgroup/1.0.2/js/dataTables.rowGroup.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.js"></script>

    <link href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.colVis.min.js"></script>

    @*<script src="https://code.jquery.com/jquery-1.12.4.js"></script>*@
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="Index">Food List</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogFood" asp-action="Index">Log</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyFood - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>